In [1]:
import numpy as np
import pandas as pd

In [2]:
anime = pd.read_csv('anime.csv')
ratings = pd.read_csv('rating.csv')

In [5]:
anime.info()
#anime_ratings= anime.merge(ratings,on='anime_id')
#anime_ratings.shape
#anime_ratings['members'].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   anime_id  12294 non-null  int64  
 1   name      12294 non-null  object 
 2   genre     12232 non-null  object 
 3   type      12269 non-null  object 
 4   episodes  12294 non-null  object 
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64  
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB


In [21]:
#anime_ratings['members'].drop()

ValueError: Need to specify at least one of 'labels', 'index' or 'columns'

In [6]:
#anime_ratings.drop('members')

KeyError: "['members'] not found in axis"

In [7]:
#anime_ratings.describe()

anime_id      rating_x       members       user_id      rating_y
count  7.813727e+06  7.813721e+06  7.813727e+06  7.813727e+06  7.813727e+06
mean   8.909045e+03  7.653127e+00  1.786208e+05  3.672795e+04  6.144036e+00
std    8.883923e+03  6.730287e-01  1.881764e+05  2.099795e+04  3.727796e+00
min    1.000000e+00  1.670000e+00  2.900000e+01  1.000000e+00 -1.000000e+00
25%    1.240000e+03  7.270000e+00  4.403000e+04  1.897400e+04  6.000000e+00
50%    6.213000e+03  7.680000e+00  1.104700e+05  3.679100e+04  7.000000e+00
75%    1.409300e+04  8.130000e+00  2.442680e+05  5.475700e+04  9.000000e+00
max    3.451900e+04  9.500000e+00  1.013917e+06  7.351600e+04  1.000000e+01

In [8]:
#anime_ratings.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7813727 entries, 0 to 7813726
Data columns (total 9 columns):
 #   Column    Dtype  
---  ------    -----  
 0   anime_id  int64  
 1   name      object 
 2   genre     object 
 3   type      object 
 4   episodes  object 
 5   rating_x  float64
 6   members   int64  
 7   user_id   int64  
 8   rating_y  int64  
dtypes: float64(1), int64(4), object(4)
memory usage: 854.1+ MB


In [6]:
anime.drop(['members'],axis=1)

anime_id                                               name  \
0         32281                                     Kimi no Na wa.   
1          5114                   Fullmetal Alchemist: Brotherhood   
2         28977                                           Gintama°   
3          9253                                        Steins;Gate   
4          9969                                      Gintama&#039;   
...         ...                                                ...   
12289      9316       Toushindai My Lover: Minami tai Mecha-Minami   
12290      5543                                        Under World   
12291      5621                     Violence Gekiga David no Hoshi   
12292      6133  Violence Gekiga Shin David no Hoshi: Inma Dens...   
12293     26081                   Yasuji no Pornorama: Yacchimae!!   

                                                   genre   type episodes  \
0                   Drama, Romance, School, Supernatural  Movie        1   
1      Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64   
2      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
3                                       Sci-Fi, Thriller     TV       24   
4      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
...                                                  ...    ...      ...   
12289                                             Hentai    OVA        1   
12290                                             Hentai    OVA        1   
12291                                             Hentai    OVA        4   
12292                                             Hentai    OVA        1   
12293                                             Hentai  Movie        1   

       rating  
0        9.37  
1        9.26  
2        9.25  
3        9.17  
4        9.16  
...       ...  
12289    4.15  
12290    4.28  
12291    4.88  
12292    4.98  
12293    5.46  

[12294 rows x 6 columns]

In [7]:
anime.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [8]:
anime['genre'].value_counts()

Hentai                                                  823
Comedy                                                  523
Music                                                   301
Kids                                                    199
Comedy, Slice of Life                                   179
                                                       ... 
Adventure, Drama, Fantasy, Game, Sci-Fi                   1
Adventure, Demons, Fantasy, Historical                    1
Action, Comedy, Drama, Mecha, Music, Sci-Fi, Shounen      1
Action, Comedy, Fantasy, Mecha, Sci-Fi, Shounen           1
Hentai, Slice of Life                                     1
Name: genre, Length: 3264, dtype: int64

In [9]:
anime.dropna(inplace=True)

In [10]:
anime.isnull().sum()

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

In [12]:
anime.duplicated().sum()

0

In [16]:
#anime_ratings['genre'] = anime_ratings['genre'].apply(lambda x:[i.replace(' ','') for i in x])

In [13]:
anime.head()

anime_id                              name  \
0     32281                    Kimi no Na wa.   
1      5114  Fullmetal Alchemist: Brotherhood   
2     28977                          Gintama°   
3      9253                       Steins;Gate   
4      9969                     Gintama&#039;   

                                               genre   type episodes  rating  \
0               Drama, Romance, School, Supernatural  Movie        1    9.37   
1  Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64    9.26   
2  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.25   
3                                   Sci-Fi, Thriller     TV       24    9.17   
4  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.16   

   members  
0   200630  
1   793665  
2   114262  
3   673572  
4   151266

In [14]:
anime['tags'] = anime['genre']+anime['type']

In [15]:
anime.head()

anime_id                              name  \
0     32281                    Kimi no Na wa.   
1      5114  Fullmetal Alchemist: Brotherhood   
2     28977                          Gintama°   
3      9253                       Steins;Gate   
4      9969                     Gintama&#039;   

                                               genre   type episodes  rating  \
0               Drama, Romance, School, Supernatural  Movie        1    9.37   
1  Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64    9.26   
2  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.25   
3                                   Sci-Fi, Thriller     TV       24    9.17   
4  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.16   

   members                                               tags  
0   200630          Drama, Romance, School, SupernaturalMovie  
1   793665  Action, Adventure, Drama, Fantasy, Magic, Mili...  
2   114262  Action, Comedy, Historical, Parody, Samurai, S...  
3   673572                                 Sci-Fi, ThrillerTV  
4   151266  Action, Comedy, Historical, Parody, Samurai, S...

In [16]:
new = anime[['anime_id','name','tags']]

In [17]:
new.head()

anime_id                              name  \
0     32281                    Kimi no Na wa.   
1      5114  Fullmetal Alchemist: Brotherhood   
2     28977                          Gintama°   
3      9253                       Steins;Gate   
4      9969                     Gintama&#039;   

                                                tags  
0          Drama, Romance, School, SupernaturalMovie  
1  Action, Adventure, Drama, Fantasy, Magic, Mili...  
2  Action, Comedy, Historical, Parody, Samurai, S...  
3                                 Sci-Fi, ThrillerTV  
4  Action, Comedy, Historical, Parody, Samurai, S...

In [32]:
#new.headnew['tags'].apply(lambda x:"".join(x))

0          Drama, Romance, School, SupernaturalMovie
1          Drama, Romance, School, SupernaturalMovie
2          Drama, Romance, School, SupernaturalMovie
3          Drama, Romance, School, SupernaturalMovie
4          Drama, Romance, School, SupernaturalMovie
                             ...                    
7813722                                    HentaiOVA
7813723                                    HentaiOVA
7813724                                    HentaiOVA
7813725                                  HentaiMovie
7813726                                  HentaiMovie
Name: tags, Length: 7813611, dtype: object

In [33]:
new.head()

anime_id            name                                       tags
0     32281  Kimi no Na wa.  Drama, Romance, School, SupernaturalMovie
1     32281  Kimi no Na wa.  Drama, Romance, School, SupernaturalMovie
2     32281  Kimi no Na wa.  Drama, Romance, School, SupernaturalMovie
3     32281  Kimi no Na wa.  Drama, Romance, School, SupernaturalMovie
4     32281  Kimi no Na wa.  Drama, Romance, School, SupernaturalMovie

In [18]:
new['tags']=new['tags'].apply(lambda x:x.lower())

C:\Users\ragin\AppData\Local\Temp/ipykernel_14200/3373542102.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new['tags']=new['tags'].apply(lambda x:x.lower())


In [19]:
new.head()

anime_id                              name  \
0     32281                    Kimi no Na wa.   
1      5114  Fullmetal Alchemist: Brotherhood   
2     28977                          Gintama°   
3      9253                       Steins;Gate   
4      9969                     Gintama&#039;   

                                                tags  
0          drama, romance, school, supernaturalmovie  
1  action, adventure, drama, fantasy, magic, mili...  
2  action, comedy, historical, parody, samurai, s...  
3                                 sci-fi, thrillertv  
4  action, comedy, historical, parody, samurai, s...

In [20]:
new['tags'][0]

'drama, romance, school, supernaturalmovie'

In [39]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [40]:
vectors = cv.fit_transform(new['tags']).toarray()

In [41]:
vectors.shape

(12017, 257)

In [42]:
vectors[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [30]:
cv.get_feature_names()

['action',
 'adventure',
 'arts',
 'cars',
 'comedy',
 'comedymovie',
 'comedyona',
 'comedyova',
 'comedyspecial',
 'comedytv',
 'dementia',
 'dementiamovie',
 'demons',
 'drama',
 'dramamovie',
 'ecchi',
 'fantasy',
 'fantasymovie',
 'fantasyova',
 'fantasyspecial',
 'fantasytv',
 'fi',
 'fimovie',
 'fiona',
 'fiova',
 'fispecial',
 'fitv',
 'game',
 'harem',
 'hentai',
 'hentaiova',
 'historical',
 'historicalmovie',
 'historicaltv',
 'horror',
 'kids',
 'kidsmovie',
 'kidsova',
 'kidsspecial',
 'kidstv',
 'life',
 'lifemovie',
 'lifeona',
 'lifeova',
 'lifespecial',
 'lifetv',
 'magic',
 'magicova',
 'magictv',
 'martial',
 'mecha',
 'military',
 'music',
 'musicmovie',
 'musicmusic',
 'mystery',
 'parody',
 'police',
 'power',
 'powermovie',
 'powerova',
 'powerspecial',
 'powertv',
 'psychological',
 'romance',
 'romanceova',
 'romancetv',
 'samurai',
 'school',
 'schoolova',
 'schoolspecial',
 'schooltv',
 'sci',
 'seinen',
 'seinenova',
 'seinentv',
 'shoujo',
 'shoujomovie',
 

In [43]:
from sklearn.metrics.pairwise import cosine_similarity

In [44]:
similarity = cosine_similarity(vectors)

In [45]:
similarity

array([[1.        , 0.18898224, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.18898224, 1.        , 0.26726124, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.26726124, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [46]:
similarity[0]

array([1.        , 0.18898224, 0.        , ..., 0.        , 0.        ,
       0.        ])

In [47]:
similarity[1]


array([0.18898224, 1.        , 0.26726124, ..., 0.        , 0.        ,
       0.        ])

In [48]:
#to remove punctuation marks and symbol from name column
import string
new['name'] = new['name'].str.replace(r'[^\w\s]+', '')
    

C:\Users\ragin\AppData\Local\Temp/ipykernel_14200/126202344.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  new['name'] = new['name'].str.replace(r'[^\w\s]+', '')
C:\Users\ragin\AppData\Local\Temp/ipykernel_14200/126202344.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new['name'] = new['name'].str.replace(r'[^\w\s]+', '')


In [49]:
new.head()

anime_id                             name  \
0     32281                    Kimi no Na wa   
1      5114  Fullmetal Alchemist Brotherhood   
2     28977                          Gintama   
3      9253                       SteinsGate   
4      9969                       Gintama039   

                                                tags  
0          drama, romance, school, supernaturalmovie  
1  action, adventure, drama, fantasy, magic, mili...  
2  action, comedy, historical, parody, samurai, s...  
3                                 sci-fi, thrillertv  
4  action, comedy, historical, parody, samurai, s...

In [83]:
new[new['name']=='Bloodivores'].index[0]

6750

In [70]:
def recommend(movie):
    an_index = new[new['name'] == movie].index[0]
    distances = similarity[an_index]
    anime_list = sorted(list(enumerate(distances)),reverse=True,key = lambda x: x[1])[1:6]
    
    for i in anime_list:
        print(new.name.iloc[i[0]])

In [72]:
recommend('One Piece')

One Piece Episode of Merry  Mou Hitori no Nakama no Monogatari
One Piece Episode of Nami  Koukaishi no Namida to Nakama no Kizuna
One Piece Episode of Sabo  3 Kyoudai no Kizuna Kiseki no Saikai to Uketsugareru Ishi
Shingeki no Kyojin
Dragon Ball Z


In [69]:
new.name.iloc[48]

'Mushishi Special Hihamukage'

In [73]:
import pickle

In [77]:
pickle.dump(new.to_dict(), open('anime_dict.pkl','wb'))

In [79]:
new['name'].values

array(['Kimi no Na wa', 'Fullmetal Alchemist Brotherhood', 'Gintama', ...,
       'Violence Gekiga David no Hoshi',
       'Violence Gekiga Shin David no Hoshi Inma Densetsu',
       'Yasuji no Pornorama Yacchimae'], dtype=object)

In [80]:
pickle.dump(new.to_dict(),open('anime_dict.pkl','wb'))

In [81]:
new.to_dict()

{'anime_id': {0: 32281,
  1: 5114,
  2: 28977,
  3: 9253,
  4: 9969,
  5: 32935,
  6: 11061,
  7: 820,
  8: 15335,
  9: 15417,
  10: 4181,
  11: 28851,
  12: 918,
  13: 2904,
  14: 28891,
  15: 199,
  16: 23273,
  17: 24701,
  18: 12355,
  19: 1575,
  20: 263,
  21: 44,
  22: 1,
  23: 30276,
  24: 164,
  25: 7311,
  26: 17074,
  27: 21939,
  28: 457,
  29: 2001,
  30: 245,
  31: 32983,
  32: 5258,
  33: 28957,
  34: 11665,
  35: 431,
  36: 11741,
  37: 31757,
  38: 19,
  39: 12365,
  40: 1535,
  41: 32366,
  42: 30654,
  43: 20583,
  44: 19647,
  45: 4282,
  46: 10379,
  47: 22135,
  48: 21329,
  49: 31043,
  50: 7785,
  51: 3297,
  52: 30709,
  53: 6114,
  54: 31240,
  55: 4565,
  56: 5300,
  57: 9989,
  58: 24415,
  59: 11577,
  60: 10408,
  61: 28171,
  62: 32995,
  63: 21899,
  64: 26055,
  65: 7472,
  66: 777,
  67: 22535,
  68: 28735,
  69: 12431,
  70: 28805,
  71: 578,
  72: 16894,
  73: 5028,
  74: 21,
  75: 801,
  76: 31933,
  77: 5205,
  78: 17389,
  79: 170,
  80: 10162,
  

In [82]:
pickle.dump(similarity, open('similarity.pkl','wb'))